name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Add Dir
              shell: bash
              run: |
                  mkdir RunnerWay